declare const classNames: {
  readonly dialog: "dialog";
  readonly selectSingleValue: "selectSingleValue";
  readonly input: "input";
  readonly radio: "radio";
  readonly checked: "checked";
  readonly label: "label";
  readonly selectMenu: "selectMenu";
  readonly lead: "lead";
  readonly context: "context";
  readonly heading: "heading";
  readonly writes: "writes";
  readonly single: "single";
  readonly warning: "warning";
  readonly icon: "icon";
  readonly changed: "changed";
  readonly field: "field";
  readonly hint: "hint";
  readonly error: "error";
  readonly list: "list";
  readonly candidates: "candidates";
  readonly candidate: "candidate";
  readonly chosen: "chosen";
  readonly ineligible: "ineligible";
  readonly reason: "reason";
  readonly plan: "plan";
};
export = classNames;
