declare const classNames: {
  readonly errorText: "errorText";
  readonly coordinate: "coordinate";
  readonly snapshots: "snapshots";
  readonly metadata: "metadata";
  readonly generated: "generated";
  readonly windows: "windows";
  readonly tableCell: "tableCell";
  readonly name: "name";
  readonly key: "key";
  readonly value: "value";
  readonly server: "server";
  readonly first: "first";
  readonly last: "last";
  readonly windowState: "windowState";
  readonly type: "type";
  readonly tablespace: "tablespace";
  readonly condition: "condition";
  readonly started: "started";
  readonly duration: "duration";
  readonly door: "door";
  readonly secretKey: "secretKey";
  readonly secretRef: "secretRef";
};
export = classNames;
